[project]
name = "build-rag-agent-google-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rahul Solanki", email = "rahulsolankib@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-adk==2.2.0",
    "streamlit==1.56.0",
]

[project.scripts]
build-rag-agent-google-adk = "build_rag_agent_google_adk:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
